- min

- max

- len

- sum

- mean

- median

- mode

- variance

- covariance

- corelation

- percentile

- quantile


In [ ]:
xi ==== raw data

- mean  === x-bar

- median === xi

In [2]:
import numpy as np

In [2]:
l = list(range(1,20))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

## list to array

In [3]:
arr1 = np.array(l)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

## array to list

In [4]:
arr1.tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

### min, max, sum ,

In [8]:
Min = np.min(arr1)
print(Min)
MAx = np.max(arr1)
print(MAx)
Summ = np.sum(arr1)
print(Summ)


1
19
190


## len

In [16]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [19]:
len(arr1)

19

## count no.of non-zero's

- count_nonzero

In [11]:
np.count_nonzero(arr1)

np.int64(19)

## mean, median , mode

In [13]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [15]:
Mean = np.mean(arr1)
print(Mean)

Median = np.median(arr1)
print(Median)

10.0
10.0


### you can also do in other ways

In [24]:
ar = np.array([1,2,3,4])
summ = sum(ar)
lenn = len(ar)
mean = summ/lenn
print(f'Mean: {mean}')

Mean: 2.5


### median for Even length of numbers

In [32]:
ar = np.array([1,2,3,4])
n = len(ar)

# even or odd
if n%2 == 0:
    median = (  ar[ n//2 ] + ar[ n//2 - 1] ) / 2
else:
    median  = ar[ n//2]
median

np.float64(2.5)

In [5]:
arr1 = np.array([3,2,1,1,5,5])
arr1.sort()
count = {}
for i in arr1:
    if i not in count:
        count[i] = 1
    else:
        count[i] += 1
print(count)

{np.int64(1): 2, np.int64(2): 1, np.int64(3): 1, np.int64(5): 2}


## another way for mode

- there is no **mode function** in Numpy

- use `statitics`

In [40]:
from statistics import mode
mode(arr1)

np.int64(1)

## variance()

- find the mean

- subtract the mean from array    array - mean

- square each element

- summation == add above values

- divide them length of the array

<img src="https://images.ctfassets.net/pdf29us7flmy/4UEXUFiVFUgsNA9fZOOQf2/b9e09d7447df4f0253a145ad853eb883/resized.png?w=720&amp;q=100&amp;fm=jpg" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 694px; height: 145px; margin: 0px; width: 357px;" alt="Variance: Definition, Formula and Step-by-Step Examples | Indeed.com" jsname="kn3ccd">

In [52]:
l = [ 1 , 2,  3,  4,  5,  6,  7,  8 , 9, 10, 11, 12,13, 14, 15, 16, 17, 18, 19]
arr = np.array(l)
print(arr)

#mean
mean = np.mean(arr)
print(mean)

#all squares
sqs = (arr - mean)**2
print(sqs)

# all add summation
total = sum(sqs)
print(total)

#divide them with the len(array)
var = total/(len(arr))
print(var)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
10.0
[81. 64. 49. 36. 25. 16.  9.  4.  1.  0.  1.  4.  9. 16. 25. 36. 49. 64.
 81.]
570.0
30.0


## also can write like this

In [55]:
l = [ 1 , 2,  3,  4,  5,  6,  7,  8 , 9, 10, 11, 12,13, 14, 15, 16, 17, 18, 19]
arr1 = np.array(l)
print(arr1)

#mean
arr1_mean = np.mean(arr1)
arr2 = arr1 - arr1_mean
arr3 = np.square(arr2)
var = np.sum(arr3) / len(arr1)
print(f'Variance: {var}')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Variance: 30.0


In [58]:
### in few lines

l = [ 1 , 2,  3,  4,  5,  6,  7,  8 , 9, 10, 11, 12,13, 14, 15, 16, 17, 18, 19]
arr1 = np.array(l)
print(arr1)

var = np.sum(   np.square( arr1 - np.mean(arr1)  ) ) / len(arr1)
var              ###########################
                    # squaring of all xi - xbar

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


np.float64(30.0)

## std deviation

- apply sqrt for variance


<img src="https://kierandixon.com/wp-content/uploads/population-standard-deviation-equation.png" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 539px; height: 198px; margin: 0px; width: 357px;" alt="How To Calculate Standard Deviation In Google Sheets - Kieran Dixon" jsname="kn3ccd">

In [65]:
l = [ 1 , 2,  3,  4,  5,  6,  7,  8 , 9, 10, 11, 12,13, 14, 15, 16, 17, 18, 19]
arr1 = np.array(l)
print(arr1)

mean = np.mean(arr1)
sum_sq =  sum( np.square(arr1 - mean) )

var = sum_sq / len(arr1)+
#std deviation

std_d = np.sqrt(var)
print(f'Std deviation: {round(std_d, 3 )}')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Std deviation: 5.477


## in few lines

In [68]:
l = [ 1 , 2,  3,  4,  5,  6,  7,  8 , 9, 10, 11, 12,13, 14, 15, 16, 17, 18, 19]
arr1 = np.array(l)
print(arr1)

std = np.sqrt( sum( np.square( arr1 - np.mean(arr1) ) ) / len(arr1) )
print(f'std: {round(std, 3)}')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
std: 5.477


## percentage :     depends on total marks and scored marks

#### example  marks

-  how many marks you have got out of total    ===  percentage

    - depends only on you

## percentile    == depends on total strength

- how many students are scored less than or equal to your marks

    - how many are behind you 

    - how much better you are compared to others

    - at what position you are


In [ ]:
l = [ 1 , 2,  3,  4,  5,  6,  7,  8 , 9, 10, 11, 12,13, 14, 15, 16, 17, 18, 19]
arr1 = np.array(l)
print(arr1)


# a : array_like of real numbers
#     Input array or object that can be converted to an array.

# q : array_like of float
#     Percentage or sequence of percentages for the percentiles to compute.
#     Values must be between 0 and 100 inclusive.

np.percentile(a , q) # ===  a : array ,  q : how much percentile

                        # it will give the value  of that percentile


In [70]:
np.percentile(arr1, 50)    # exactly   half

np.float64(10.0)

In [73]:
np.percentile(arr1, 5)

np.float64(1.9)

In [71]:
np.percentile(arr1, 25)

np.float64(5.5)

In [ ]:
np.quantile()

# q : array_like of float
#     Probability or sequence of probabilities of the quantiles to compute.
#     Values must be between 0 and 1 inclusive.

In [74]:
np.quantile(arr1, 0.5)

np.float64(10.0)

In [79]:
np.quantile(arr1, 0.99)

np.float64(18.82)

## distance formula

- take two np array

    - one array : (x1,y1)
 
    - another array : (x2,y2)
 
- apply squaring both arrays

- sum them

- apply sqrt

<img src="https://media.hswstatic.com/eyJidWNrZXQiOiJjb250ZW50Lmhzd3N0YXRpYy5jb20iLCJrZXkiOiJnaWZcL2Rpc3RhbmNlLWZvcm11bGEuanBnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjoiMTIwMCJ9fX0=" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 1200px; height: 201px; margin: 0px; width: 357px;" alt="Distance Formula: Finding the Distance Between Two Points | HowStuffWorks" jsname="kn3ccd">

In [84]:
l1 = [3,5 ]        # (x1,y1)
l2 = [10,20]       # (x2, y2)
arr1 = np.array(l1)
arr2 = np.array(l2)

# squaring
sq = np.square(arr2 - arr1)

# sum
total = sum(sq)
total

# sqrt
np.sqrt(total)

np.float64(16.55294535724685)

In [85]:
distance = np.sqrt( sum ( np.square(arr2 - arr1 ) ) )
distance

np.float64(16.55294535724685)

## covariance

- two means ====  for two arrays

- subtract every value form their mean  and multiply both

- sum the total

- divide them by N

<img src="https://www.alpharithms.com/wp-content/uploads/1156/covariance-equation-diagram.jpg" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 1366px; width: 357px; height: 201px; margin: 0px;" alt="Covariance: Finding Direction Among Variable Relationships - αlphαrithms" jsname="kn3ccd">

- your dataset has all population data   :  / n


- your dataset has only few no.of data (sample)   :  / n- 1


- Ex:
    - if the college ==> 1000 stud
    - collected data from all  and estimating   : /  n
    - collected data from only 100 and
        - want to estimate population(1000)    : / n - 1

In [ ]:
Actual data
2   4   6   8
↓   ↓   ↓   ↓
Observe ALL values
↓
Calculate mean = 5
↓
Calculate ALL deviations
-3  -1  +1  +3
↓
One deviation is mathematically dependent
↓
But we STILL USE all deviations
↓
Degrees of freedom = n - 1


- the deviations ==> are equal to Zero (0)

if i give   -3  -1  +1  ?     you will say  the fourth value ,      -3 + -1 + 1 + -3  = 0

        **last value is dependent on MEAN**



In [98]:
l1=list(range(1,11))
l2=list(range(21,31))

arr1 = np.array(l1)
arr2 = np.array(l2)

# means 
arr1_mean = np.mean(arr1)
arr2_mean = np.mean(arr2)

s = (arr1 - arr1_mean) * (arr2 - arr2_mean)

cov = sum (s) / len(arr1)
cov

np.float64(8.25)

<img src="https://zerodha.com/varsity/wp-content/uploads/2017/04/Correlation-Formula.png" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 428px; height: 45px; margin: 45px 0px; width: 120px;" alt="Stock Portfolio Correlation Matrix &amp; Variance Calculation" jsname="kn3ccd">

<img src="https://www.alpharithms.com/wp-content/uploads/1074/simplified-correlation-coefficient-formula-vs-expanded.jpg" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 1366px; height: 67px; margin: 34px 0px; width: 120px;" alt="Correlation Analysis: Quantifying Linear Relationships Between Features -  αlphαrithms" jsname="kn3ccd">

In [13]:
import numpy as np
l1=list(range(1,11))
l2=list(range(21,31))

arr1 = np.array(l1)
arr2 = np.array(l2)

arr1_mean = np.mean(arr1)
arr2_mean =  np.mean(arr2)

cov_numerator = round  (   np.sum( (arr1 - arr1_mean) * (arr2 - arr2_mean) ) , 3 )

std_arr1 =  round (  np.sqrt( np.sum ( np.square( arr1 - arr1_mean) ) ) , 3 )
std_arr2 =  round (  np.sqrt( np.s
    um ( np.square( arr2 - arr2_mean) ) ) , 3 )

std = std_arr1 * std_arr2

correlation = round(cov_numerator/std,3)
correlation

np.float64(1.0)