In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

In [ ]:
arr1.ndim
arr1.shape
arr1.size
arr1.dtype
type(arr1)

## ndimensions

In [3]:
k = [1,2,3]
arr1 = np.array(k)
arr1

array([1, 2, 3])

In [4]:
arr1.ndim

1

In [5]:
type(arr1)

numpy.ndarray

## shape

- returns == how many rows and columns

In [9]:
arr1

array([1, 2, 3])

In [7]:
arr1.shape

(3,)

## size 

- returns == how many elements are avaialble

In [8]:
arr1

array([1, 2, 3])

In [10]:
arr1.size

3

## 2D 

#### stores lists

In [ ]:
a = np.array([
    [10,20],
    [30,40],
    [50,60]
])

In [11]:
l1 = [1,2,3,4]
l2 = [10,20,30,40]
np.array(l1,l2)

TypeError: Field elements must be 2- or 3-tuples, got '10'

#### data should be passed as single element

In [12]:
l1 = [1,2,3,4]
l2 = [10,20,30,40]
np.array([l1,l2])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [17]:
l1 = [1,2,3,4]
l2 = [10,20,30,40]
data = [l1,l2]
arr=np.array(data)
arr

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [18]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 4)
8
int64


## upcasting

- if we element as other datatype ===
    - all others also changed to that type

In [19]:
l1 = [1,2,3,4]
l2 = [10,20,30,40.0]    # 40.0 float
data = [l1,l2]
arr=np.array(data)
arr                       # all converted to float

array([[ 1.,  2.,  3.,  4.],
       [10., 20., 30., 40.]])

In [21]:
arr.dtype      #float  64 == o.s

dtype('float64')

In [32]:
l1 = [1,2,3,4]
l2 = [10,20,30,40]
l3 = ['A','B','C','D']
data = [l1,l2,l3]
arr=np.array(data)
print(data)
print(arr)

[[1, 2, 3, 4], [10, 20, 30, 40], ['A', 'B', 'C', 'D']]
[['1' '2' '3' '4']
 ['10' '20' '30' '40']
 ['A' 'B' 'C' 'D']]


In [33]:
arr.size, arr.shape, arr.ndim

(12, (3, 4), 2)

## dimensions

In [40]:
l1 = [1,2,3,4]
print(np.array(l1))   # [1]
print(np.array([l1]).ndim)    # [[1]]
print(np.array([[l1]]).ndim)   # [[[1]]]

[1 2 3 4]
2
3


# 3D

### stores group of lists

In [ ]:
a = np.array([

[
 [10,20],
 [30,40],
 [50,60]
],

[
 [70,80],
 [90,100],
 [110,120]
]

])

In [42]:
l1= [1,2,3,4]
l2 = [10,20,30,40]
l3 = ['A','B','C','D']
arr3 = np.array([[l1,l2,l3]])
arr3

array([[['1', '2', '3', '4'],
        ['10', '20', '30', '40'],
        ['A', 'B', 'C', 'D']]], dtype='<U21')

In [ ]:
1dim        2dim         3dim
 |           |             |
(m, )       (m,n)        (m,n,k)